README updates
hashicorp/terraform-google-nomad pull request #14
Opened 2019-10-31 19:49 UTC by yorinasub17

This updates the README to be in line with our new format.

2019-11-01 08:49 UTC, robmorgan requested changes
minor thing

2019-11-01 08:49 UTC, robmorgan commented on README.md
> +* [root](https://github.com/hashicorp/terraform-google-nomad/tree/master): The root folder is *an example* of how to use the [nomad-cluster module](https://github.com/hashicorp/terraform-google-nomad
```suggestion
* [root](https://github.com/hashicorp/terraform-google-nomad/tree/master): The root folder is *an example* of how to use the [nomad-cluster module](https://github.com/hashicorp/terraform-google-nomad/tree/master/modules/nomad-cluster) module to deploy a [Nomad](https://www.nomadproject.io/) cluster in [GCP](https://cloud.google.com/). The Terraform Registry requires the root of every repo to contain Terraform code, so we've put one of the examples there. This example is great for learning and experimenting, but for production use, please use the underlying modules in the [modules folder](https://github.com/hashicorp/terraform-google-nomad/tree/master/modules) directly.
```

2019-11-01 17:48 UTC, yorinasub17 commented on README.md
> +* [root](https://github.com/hashicorp/terraform-google-nomad/tree/master): The root folder is *an example* of how to use the [nomad-cluster module](https://github.com/hashicorp/terraform-google-nomad
Good catch!

2019-11-01 17:48 UTC, yorinasub17 commented
FYI I don't have the permissions to merge this :)

2022-03-12 17:18 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform-google-nomad?pullRequest=14)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform-google-nomad?pullRequest=14)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform-google-nomad?pullRequest=14).</sub>

2022-08-09 20:43 UTC, closed without merging

2022-08-09 20:43 UTC, yorinasub17 commented
Closing as outdated